-- SQL seed for psychology landing content by Mexican state
SET NAMES utf8mb4;
SET time_zone = '+00:00';
CREATE DATABASE IF NOT EXISTS php_curso CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE php_curso;

DROP TABLE IF EXISTS mx_testimonials;
DROP TABLE IF EXISTS mx_services;
DROP TABLE IF EXISTS mx_states;

CREATE TABLE mx_states (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  hero_h1 VARCHAR(255) NOT NULL,
  hero_p VARCHAR(160) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mx_services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  state_id INT NOT NULL,
  icon VARCHAR(8) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(160) NOT NULL,
  FOREIGN KEY (state_id) REFERENCES mx_states(id) ON DELETE CASCADE,
  INDEX (state_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mx_testimonials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  state_id INT NOT NULL,
  content VARCHAR(280) NOT NULL,
  FOREIGN KEY (state_id) REFERENCES mx_states(id) ON DELETE CASCADE,
  INDEX (state_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO mx_states (name, slug, hero_h1, hero_p) VALUES
('Aguascalientes', 'aguascalientes', 'Información de la sesión psicológica en Aguascalientes', 'Atención psicológica accesible en Aguascalientes para mejorar tu bienestar.'),
('Baja California', 'baja-california', 'Información de la sesión psicológica en Baja California', 'Atención psicológica accesible en Baja California para mejorar tu bienestar.'),
('Baja California Sur', 'baja-california-sur', 'Información de la sesión psicológica en Baja California Sur', 'Profesionales certificados te acompañan en Baja California Sur con enfoque humano.'),
('Campeche', 'campeche', 'Información de la sesión psicológica en Campeche', 'Agenda tu sesión en Campeche y comienza un proceso de cambio seguro.'),
('Coahuila', 'coahuila', 'Información de la sesión psicológica en Coahuila', 'Agenda tu sesión en Coahuila y comienza un proceso de cambio seguro.'),
('Colima', 'colima', 'Información de la sesión psicológica en Colima', 'Agenda tu sesión en Colima y comienza un proceso de cambio seguro.'),
('Chiapas', 'chiapas', 'Información de la sesión psicológica en Chiapas', 'Atención psicológica accesible en Chiapas para mejorar tu bienestar.'),
('Chihuahua', 'chihuahua', 'Información de la sesión psicológica en Chihuahua', 'Atención psicológica accesible en Chihuahua para mejorar tu bienestar.'),
('Ciudad De México', 'ciudad-de-mexico', 'Información de la sesión psicológica en Ciudad De México', 'En Ciudad De México ofrecemos apoyo breve y efectivo para tu salud mental.'),
('Durango', 'durango', 'Información de la sesión psicológica en Durango', 'Atención psicológica accesible en Durango para mejorar tu bienestar.'),
('Guanajuato', 'guanajuato', 'Información de la sesión psicológica en Guanajuato', 'Atención psicológica accesible en Guanajuato para mejorar tu bienestar.'),
('Guerrero', 'guerrero', 'Información de la sesión psicológica en Guerrero', 'Atención psicológica accesible en Guerrero para mejorar tu bienestar.'),
('Hidalgo', 'hidalgo', 'Información de la sesión psicológica en Hidalgo', 'Agenda tu sesión en Hidalgo y comienza un proceso de cambio seguro.'),
('Jalisco', 'jalisco', 'Información de la sesión psicológica en Jalisco', 'Agenda tu sesión en Jalisco y comienza un proceso de cambio seguro.'),
('México', 'mexico', 'Información de la sesión psicológica en México', 'Atención psicológica accesible en México para mejorar tu bienestar.'),
('Michoacán', 'michoacan', 'Información de la sesión psicológica en Michoacán', 'Agenda tu sesión en Michoacán y comienza un proceso de cambio seguro.'),
('Morelos', 'morelos', 'Información de la sesión psicológica en Morelos', 'En Morelos ofrecemos apoyo breve y efectivo para tu salud mental.'),
('Nayarit', 'nayarit', 'Información de la sesión psicológica en Nayarit', 'Agenda tu sesión en Nayarit y comienza un proceso de cambio seguro.'),
('Nuevo León', 'nuevo-leon', 'Información de la sesión psicológica en Nuevo León', 'En Nuevo León ofrecemos apoyo breve y efectivo para tu salud mental.'),
('Oaxaca', 'oaxaca', 'Información de la sesión psicológica en Oaxaca', 'Profesionales certificados te acompañan en Oaxaca con enfoque humano.'),
('Puebla', 'puebla', 'Información de la sesión psicológica en Puebla', 'Atención psicológica accesible en Puebla para mejorar tu bienestar.'),
('Querétaro', 'queretaro', 'Información de la sesión psicológica en Querétaro', 'Agenda tu sesión en Querétaro y comienza un proceso de cambio seguro.'),
('Quintana Roo', 'quintana-roo', 'Información de la sesión psicológica en Quintana Roo', 'En Quintana Roo ofrecemos apoyo breve y efectivo para tu salud mental.'),
('San Luis Potosí', 'san-luis-potosi', 'Información de la sesión psicológica en San Luis Potosí', 'Profesionales certificados te acompañan en San Luis Potosí con enfoque humano.'),
('Sinaloa', 'sinaloa', 'Información de la sesión psicológica en Sinaloa', 'Profesionales certificados te acompañan en Sinaloa con enfoque humano.'),
('Sonora', 'sonora', 'Información de la sesión psicológica en Sonora', 'Agenda tu sesión en Sonora y comienza un proceso de cambio seguro.'),
('Tabasco', 'tabasco', 'Información de la sesión psicológica en Tabasco', 'Agenda tu sesión en Tabasco y comienza un proceso de cambio seguro.'),
('Tamaulipas', 'tamaulipas', 'Información de la sesión psicológica en Tamaulipas', 'Profesionales certificados te acompañan en Tamaulipas con enfoque humano.'),
('Tlaxcala', 'tlaxcala', 'Información de la sesión psicológica en Tlaxcala', 'Atención psicológica accesible en Tlaxcala para mejorar tu bienestar.'),
('Veracruz', 'veracruz', 'Información de la sesión psicológica en Veracruz', 'Atención psicológica accesible en Veracruz para mejorar tu bienestar.'),
('Yucatán', 'yucatan', 'Información de la sesión psicológica en Yucatán', 'En Yucatán ofrecemos apoyo breve y efectivo para tu salud mental.'),
('Zacatecas', 'zacatecas', 'Información de la sesión psicológica en Zacatecas', 'Atención psicológica accesible en Zacatecas para mejorar tu bienestar.');
INSERT INTO mx_services (state_id, icon, title, description) VALUES
(1, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(1, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(1, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(1, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(1, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(2, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(2, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(2, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(2, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(2, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(3, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(3, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(3, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(3, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(4, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(4, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(4, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(4, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(5, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(5, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(5, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(5, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(5, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(6, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(6, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(6, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(6, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(6, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(6, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(7, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(7, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(7, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(7, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(7, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(7, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(8, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(8, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(8, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(8, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(9, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(9, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(9, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(9, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(10, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(10, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(10, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(10, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(10, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(11, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(11, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(11, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(12, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(12, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(12, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(13, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(13, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(13, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(13, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(13, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(14, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(14, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(14, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(14, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(15, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(15, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(15, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(15, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(15, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(15, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(16, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(16, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(16, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(16, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(17, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(17, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(17, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(17, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(17, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(18, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(18, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(18, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(18, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(19, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(19, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(19, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(19, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(19, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(19, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(20, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(20, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(20, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(21, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(21, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(21, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(21, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(21, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(22, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(22, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(22, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(23, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(23, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(23, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(24, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(24, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(24, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(24, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(24, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(24, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(25, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.'),
(25, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(25, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(26, '🌙', 'Higiene del sueño', 'Rutinas y hábitos para descansar mejor.'),
(26, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(26, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(27, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(27, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(27, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(28, '🏫', 'Atención en línea', 'Videollamadas seguras desde casa.'),
(28, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(28, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(28, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(28, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(29, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(29, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(29, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(30, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(30, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(30, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(30, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(31, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(31, '💬', 'Terapia de pareja', 'Mejora de la comunicación y manejo de conflictos.'),
(31, '🎯', 'Grupos de apoyo', 'Espacios para compartir y acompañarse.'),
(31, '👨‍👩‍👧', 'Mindfulness y relajación', 'Técnicas para reducir estrés y ansiedad.'),
(32, '🧘', 'Intervención en crisis', 'Apoyo inmediato para eventos de alto impacto.'),
(32, '📱', 'Psicoeducación', 'Herramientas prácticas para el día a día.'),
(32, '🩺', 'Orientación vocacional', 'Explora intereses y fortalezas personales.'),
(32, '🕊️', 'Terapia familiar', 'Acompañamiento integral para el sistema familiar.'),
(32, '🧠', 'Terapia individual', 'Sesiones breves enfocadas en objetivos claros.');
INSERT INTO mx_testimonials (state_id, content) VALUES
(1, 'Excelente trato y resultados desde la primera cita.'),
(1, 'El enfoque fue claro, respetuoso y profesional.'),
(1, 'Excelente trato y resultados desde la primera cita.'),
(1, 'Aprendí a comunicarme mejor con mi familia.'),
(2, 'Aprendí a comunicarme mejor con mi familia.'),
(2, 'Excelente trato y resultados desde la primera cita.'),
(3, 'Me sentí escuchado y acompañado en todo momento.'),
(3, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(3, 'Me sentí escuchado y acompañado en todo momento.'),
(3, 'Me sentí escuchado y acompañado en todo momento.'),
(4, 'La atención en línea fue muy cómoda y efectiva.'),
(4, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(4, 'Noté cambios positivos en pocas semanas.'),
(4, 'El enfoque fue claro, respetuoso y profesional.'),
(5, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(5, 'Me sentí escuchado y acompañado en todo momento.'),
(6, 'Noté cambios positivos en pocas semanas.'),
(6, 'El enfoque fue claro, respetuoso y profesional.'),
(7, 'Aprendí a comunicarme mejor con mi familia.'),
(7, 'El enfoque fue claro, respetuoso y profesional.'),
(7, 'El enfoque fue claro, respetuoso y profesional.'),
(7, 'Me sentí escuchado y acompañado en todo momento.'),
(8, 'Excelente trato y resultados desde la primera cita.'),
(8, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(9, 'Noté cambios positivos en pocas semanas.'),
(9, 'Aprendí a comunicarme mejor con mi familia.'),
(9, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(9, 'Excelente trato y resultados desde la primera cita.'),
(10, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(10, 'Aprendí a comunicarme mejor con mi familia.'),
(10, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(11, 'Me sentí escuchado y acompañado en todo momento.'),
(11, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(12, 'Excelente trato y resultados desde la primera cita.'),
(12, 'Me sentí escuchado y acompañado en todo momento.'),
(13, 'Noté cambios positivos en pocas semanas.'),
(13, 'Excelente trato y resultados desde la primera cita.'),
(14, 'El enfoque fue claro, respetuoso y profesional.'),
(14, 'La atención en línea fue muy cómoda y efectiva.'),
(14, 'La atención en línea fue muy cómoda y efectiva.'),
(14, 'Aprendí a comunicarme mejor con mi familia.'),
(15, 'Me sentí escuchado y acompañado en todo momento.'),
(15, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(16, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(16, 'La atención en línea fue muy cómoda y efectiva.'),
(16, 'Excelente trato y resultados desde la primera cita.'),
(16, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(17, 'La atención en línea fue muy cómoda y efectiva.'),
(17, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(17, 'Noté cambios positivos en pocas semanas.'),
(18, 'El enfoque fue claro, respetuoso y profesional.'),
(18, 'Me sentí escuchado y acompañado en todo momento.'),
(19, 'El enfoque fue claro, respetuoso y profesional.'),
(19, 'Me sentí escuchado y acompañado en todo momento.'),
(20, 'Noté cambios positivos en pocas semanas.'),
(20, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(20, 'El enfoque fue claro, respetuoso y profesional.'),
(20, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(21, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(21, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(22, 'Noté cambios positivos en pocas semanas.'),
(22, 'La atención en línea fue muy cómoda y efectiva.'),
(22, 'El enfoque fue claro, respetuoso y profesional.'),
(23, 'Aprendí a comunicarme mejor con mi familia.'),
(23, 'Noté cambios positivos en pocas semanas.'),
(23, 'Aprendí a comunicarme mejor con mi familia.'),
(24, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(24, 'Me sentí escuchado y acompañado en todo momento.'),
(25, 'Excelente trato y resultados desde la primera cita.'),
(25, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(26, 'Excelente trato y resultados desde la primera cita.'),
(26, 'La atención en línea fue muy cómoda y efectiva.'),
(26, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(27, 'La atención en línea fue muy cómoda y efectiva.'),
(27, 'Me sentí escuchado y acompañado en todo momento.'),
(27, 'La atención en línea fue muy cómoda y efectiva.'),
(28, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(28, 'Noté cambios positivos en pocas semanas.'),
(29, 'Aprendí a comunicarme mejor con mi familia.'),
(29, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(29, 'Me sentí escuchado y acompañado en todo momento.'),
(29, 'Excelente trato y resultados desde la primera cita.'),
(30, 'Aprendí a comunicarme mejor con mi familia.'),
(30, 'Las sesiones me ayudaron a entender y manejar mi ansiedad.'),
(30, 'Aprendí a comunicarme mejor con mi familia.'),
(30, 'Excelente trato y resultados desde la primera cita.'),
(31, 'Encontré herramientas prácticas para el trabajo y la casa.'),
(31, 'Aprendí a comunicarme mejor con mi familia.'),
(31, 'Aprendí a comunicarme mejor con mi familia.'),
(31, 'La atención en línea fue muy cómoda y efectiva.'),
(32, 'El enfoque fue claro, respetuoso y profesional.'),
(32, 'Aprendí a comunicarme mejor con mi familia.');